// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Drawing;
namespace RecognitionCommonTests
{
    /// <summary>
    ///This is a test class for Recognition.Locator.LocatorHelper and is intended
    ///to contain all Recognition.Locator.LocatorHelper Unit Tests
    ///</summary>
    [TestClass()]
    public class LocatorHelperTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for GetBestSubDivision (Size)
        ///</summary>
        [DeploymentItem("Recognition.Locator.dll")]
        [TestMethod()]
        public void GetBestSubDivisionTest()
        {
            Size boundingSize = new Size(1600,2000); 

            Size expected = new Size(240,180);
            Size actual;

            actual = RecognitionCommonTests.Recognition_Locator_LocatorHelperAccessor.GetBestSubDivision(boundingSize);

            Assert.AreEqual(expected, actual, "Recognition.Locator.LocatorHelper.GetBestSubDivision did not return the expected " +
                    "value.");
            
        }

    }


}
